apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-summarizer-data
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany      # RWX — несколько подов могут читать одновременно
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs  # замени на свой StorageClass
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-summarizer-runs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
