from pathlib import Path

from settings import settings


TOP_N_ANOMALIES = int(settings.CONTROL_PLANE_TOP_N_ANOMALIES)
ANALYZE_TOP_N_ANOMALIES = int(settings.CONTROL_PLANE_ANALYZE_TOP_N_ANOMALIES)
LOOPBACK_MINUTES = int(settings.CONTROL_PLANE_LOOPBACK_MINUTES)
DATA_LOOKBACK_MINUTES = int(settings.CONTROL_PLANE_DATA_LOOKBACK_MINUTES)
PREDICTION_LOOKAHEAD_MINUTES = int(settings.CONTROL_PLANE_PREDICTION_LOOKAHEAD_MINUTES)
METRICS_SOURCE = str(settings.CONTROL_PLANE_METRICS_SOURCE).strip().lower()

# Prometheus range-step is technical API detail; keep it fixed internally.
PROM_STEP = "1m"
PROM_MAX_POINTS = int(settings.CONTROL_PLANE_PROM_METRICS_MAX_POINTS)
PROM_SERIES_INDEX = int(settings.CONTROL_PLANE_PROM_METRICS_SERIES_INDEX)
PROM_QUERY = str(settings.CONTROL_PLANE_PROM_METRICS_QUERY)
PROM_URL = str(settings.CONTROL_PLANE_PROM_METRICS_URL)
PROM_USERNAME = str(settings.CONTROL_PLANE_PROM_METRICS_USERNAME)
PROM_PASSWORD = str(settings.CONTROL_PLANE_PROM_METRICS_PASSWORD)
PROM_DISABLE_SSL = bool(settings.CONTROL_PLANE_PROM_METRICS_DISABLE_SSL)

CLICKHOUSE_METRICS_QUERY = str(settings.CONTROL_PLANE_CLICKHOUSE_METRICS_QUERY)
CLICKHOUSE_METRICS_HOST = str(settings.CONTROL_PLANE_CLICKHOUSE_METRICS_HOST)
CLICKHOUSE_METRICS_PORT = int(settings.CONTROL_PLANE_CLICKHOUSE_METRICS_PORT)
CLICKHOUSE_METRICS_USERNAME = str(settings.CONTROL_PLANE_CLICKHOUSE_METRICS_USERNAME)
CLICKHOUSE_METRICS_PASSWORD = str(settings.CONTROL_PLANE_CLICKHOUSE_METRICS_PASSWORD)
CLICKHOUSE_METRICS_SECURE = bool(settings.CONTROL_PLANE_CLICKHOUSE_METRICS_SECURE)
CLICKHOUSE_PREDICTIONS_HOST = str(settings.CONTROL_PLANE_CLICKHOUSE_PREDICTIONS_HOST)
CLICKHOUSE_PREDICTIONS_PORT = int(settings.CONTROL_PLANE_CLICKHOUSE_PREDICTIONS_PORT)
CLICKHOUSE_PREDICTIONS_USERNAME = str(settings.CONTROL_PLANE_CLICKHOUSE_PREDICTIONS_USERNAME)
CLICKHOUSE_PREDICTIONS_PASSWORD = str(settings.CONTROL_PLANE_CLICKHOUSE_PREDICTIONS_PASSWORD)
CLICKHOUSE_PREDICTIONS_SECURE = bool(settings.CONTROL_PLANE_CLICKHOUSE_PREDICTIONS_SECURE)
CLICKHOUSE_PREDICTIONS_QUERY = str(settings.CONTROL_PLANE_CLICKHOUSE_PREDICTIONS_QUERY)

FORECAST_SERVICE = str(settings.CONTROL_PLANE_FORECAST_SERVICE)
FORECAST_METRIC_NAME = str(settings.CONTROL_PLANE_FORECAST_METRIC_NAME)
FORECAST_TYPE = str(settings.CONTROL_PLANE_FORECAST_TYPE)
PREDICTION_KIND = str(settings.CONTROL_PLANE_PREDICTION_KIND)

ANOMALY_ZSCORE = float(settings.CONTROL_PLANE_ANOMALY_ZSCORE)
ANOMALY_IQR_WINDOW = int(settings.CONTROL_PLANE_ANOMALY_IQR_WINDOW)
ANOMALY_IQR_SCALE = float(settings.CONTROL_PLANE_ANOMALY_IQR_SCALE)
ANOMALY_IQR_MIN_PERIODS = int(settings.CONTROL_PLANE_ANOMALY_IQR_MIN_PERIODS)
ANOMALY_DETECTOR = str(settings.CONTROL_PLANE_ANOMALY_DETECTOR)

PROCESS_ALERTS = bool(settings.CONTROL_PLANE_PROCESS_ALERTS)
SUMMARY_LOG_CHARS = int(settings.CONTROL_PLANE_SUMMARY_LOG_CHARS)
SUMMARIZER_CALLABLE = str(settings.CONTROL_PLANE_SUMMARIZER_CALLABLE).strip()
ALERT_CALLABLE = str(settings.CONTROL_PLANE_ALERT_CALLABLE).strip()
LOG_LEVEL = str(settings.CONTROL_PLANE_LOG_LEVEL).upper()

ARTIFACTS_DIR = Path(str(settings.CONTROL_PLANE_ARTIFACTS_DIR))
PLOTS_DIR = ARTIFACTS_DIR / "plots"
LOGS_DIR = ARTIFACTS_DIR / "logs"

TEST_MODE = bool(settings.CONTROL_PLANE_TEST_MODE)
TEST_MODE_SEED = int(settings.CONTROL_PLANE_TEST_SEED)
TEST_MODE_SPIKE_RATE = float(settings.CONTROL_PLANE_TEST_SPIKE_RATE)
TEST_MODE_SPIKE_SCALE = float(settings.CONTROL_PLANE_TEST_SPIKE_SCALE)
TEST_MODE_NOISE_SCALE = float(settings.CONTROL_PLANE_TEST_NOISE_SCALE)
